// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconHeroiconsOutline:bookOpen': typeof import('~icons/heroicons-outline/book-open')['default']
    'IconHeroiconsOutline:chatAlt2': typeof import('~icons/heroicons-outline/chat-alt2')['default']
    'IconHeroiconsOutline:eye': typeof import('~icons/heroicons-outline/eye')['default']
    'IconHeroiconsOutline:film': typeof import('~icons/heroicons-outline/film')['default']
    'IconHeroiconsOutline:home': typeof import('~icons/heroicons-outline/home')['default']
    'IconHeroiconsOutline:mail': typeof import('~icons/heroicons-outline/mail')['default']
    'IconHeroiconsOutline:presentationChartBar': typeof import('~icons/heroicons-outline/presentation-chart-bar')['default']
    'IconHeroiconsOutline:search': typeof import('~icons/heroicons-outline/search')['default']
    'IconHeroiconsOutline:share': typeof import('~icons/heroicons-outline/share')['default']
    'IconHeroiconsOutline:speakerphone': typeof import('~icons/heroicons-outline/speakerphone')['default']
    'IconHeroiconsOutline:x': typeof import('~icons/heroicons-outline/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
