// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconAntDesign:facebookFilled': typeof import('~icons/ant-design/facebook-filled')['default']
    'IconFa:pencilSquare': typeof import('~icons/fa/pencil-square')['default']
    'IconHeroiconsOutline:bookOpen': typeof import('~icons/heroicons-outline/book-open')['default']
    'IconHeroiconsOutline:chatAlt2': typeof import('~icons/heroicons-outline/chat-alt2')['default']
    'IconHeroiconsOutline:eye': typeof import('~icons/heroicons-outline/eye')['default']
    'IconHeroiconsOutline:film': typeof import('~icons/heroicons-outline/film')['default']
    'IconHeroiconsOutline:home': typeof import('~icons/heroicons-outline/home')['default']
    'IconHeroiconsOutline:mail': typeof import('~icons/heroicons-outline/mail')['default']
    'IconHeroiconsOutline:presentationChartBar': typeof import('~icons/heroicons-outline/presentation-chart-bar')['default']
    'IconHeroiconsOutline:share': typeof import('~icons/heroicons-outline/share')['default']
    'IconHeroiconsOutline:speakerphone': typeof import('~icons/heroicons-outline/speakerphone')['default']
    'IconHeroiconsOutline:x': typeof import('~icons/heroicons-outline/x')['default']
    'IconIc:baselinePlayCircleFilled': typeof import('~icons/ic/baseline-play-circle-filled')['default']
    'IconMdi:facebookBox': typeof import('~icons/mdi/facebook-box')['default']
    'IconMdi:githubBox': typeof import('~icons/mdi/github-box')['default']
    'IconMdi:twitterBox': typeof import('~icons/mdi/twitter-box')['default']
    'IconMdi:youtube': typeof import('~icons/mdi/youtube')['default']
    'IconPh:pencilSimpleLineBold': typeof import('~icons/ph/pencil-simple-line-bold')['default']
    'IconRi:searchLine': typeof import('~icons/ri/search-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
